name: Tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        strategy:
            matrix:
                go-version: [1.19.X, 1.20.X, 1.21.X, 1.22.X]
                platform: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.platform }}

        steps:
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ matrix.go-version }}

            - uses: actions/checkout@v4

            - name: Run Tests
              run: go test ./...
